version: "3.9"

services:
  indexador:
    build: .
    container_name: indexador
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /mnt/juridico:/dados
    restart: "no"