services:
  indexador:
    build:
      context: .
      network: host
    container_name: indexador
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /mnt/ocr-juridico:/juridico
      - /mnt/ocr-juridico-people:/people
      - /mnt/ocr-juridico-Sign:/sign
      - /mnt/ocr-juridico-sign_original_files:/sign_original_files
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 25G