services:
  indexador:
    build:
      context: .
      network: host
    container_name: indexador
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /mnt/ocr-juridico:/dados
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 25G